CREATE TABLE tanar (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Nev VARCHAR(255) NOT NULL
);

CREATE TABLE terem (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Emelet INT,
  Teremszam INT NOT NULL,
  Gepterem BOOLEAN NOT NULL,
  Nagyterem BOOLEAN NOT NULL
);

CREATE TABLE targy (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  Nev VARCHAR(255) NOT NULL,
  Felev INT NOT NULL
);

CREATE TABLE tanitja (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  TargyID INT NOT NULL,
  TanarID INT NOT NULL
);

CREATE TABLE foglalas (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  TeremID INT NOT NULL,
  TargyID INT NOT NULL,
  Esemeny VARCHAR(255),
  KezdIdo TIMESTAMP NOT NULL,
  VegIdo TIMESTAMP NOT NULL
);
